[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
solc = "0.8.25"
evm_version = "london"
optimizer = true
optimizer_runs = 800
via_ir = true
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "hardhat/=node_modules/hardhat/",
    "forge-std/=lib/forge-std/src",
]

no_match_coverage = "contracts/mocks/.*|scripts/*"

[lint]
lint_on_build = true
severity = ["high", "medium", "low", "info", "gas"]
exclude_lints = [
    "block-timestamp",
    "mixed-case-function",
    "pascal-case-struct",
    "asm-keccak256",
]

[fmt]
line_length = 120
tab_width = 4
style = "space"
bracket_spacing = true
multiline_func_header = "params_first_multi"
number_underscore = "thousands"
wrap_comments = true
docs_style = "line"
sort_imports = true
prefer_compact = "none"
single_line_imports = true

[doc]
ignore = ["**/*.t.sol"]
out = "docs"
repository = "https://github.com/DMDcoin/diamond-contracts-core"

[rpc_endpoints]
dmd_mainnet = "https://rpc.bit.diamonds"
dmd_testnet = "http://62.171.133.46:20100"

[etherscan]
dmd_mainnet = { key = "abc", url = "https://explorer.bit.diamonds/api"}
dmd_testnet = { key = "abc", url = "https://testnet-explorer.bit.diamonds/api"}

