name: Build & test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.18.0]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11.11.0
          cache: true

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm hardhat build

      - name: Run tests
        run: pnpm hardhat test

      - name: Run coverage
        run: pnpm hardhat coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
