name: Static Analysis
on:
  push:
    paths:
    #   - 'contracts/**'
      - '.github/workflows/slither.yml'
  pull_request:
    paths:
      - 'contracts/**'
      - '.github/workflows/slither.yml'

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx hardhat compile

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo snap install solc
          python -m pip install --upgrade pip
          pip3 install slither-analyzer
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Summary of static ananlysis
        run: |
          echo "Running slither"
          slither . --print human-summary
      - name: Contract summary of static ananlysis
        run: |
          echo "Running slither"
          slither . --print contract-summary
        with: |
            slither-config: slither.config.json
      - name: Function summary
        run: |
          slither . --print function-summary
        with: |
            slither-config: slither.config.json
      - name: Data dependency
        run: |
          slither . --print data-dependency
        with: |
            slither-config: slither.config.json
      - name: Inheritance
        run: |
          slither . --print inheritance
        with: |
            slither-config: slither.config.json
